apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml

profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
    artifacts:
    - image: saloni-test-image
      context: gke
      sync:
        infer:
        - '**/*'
      docker:
        dockerfile: Dockerfile

# deploying on a local cluster
- name: local
  build:
    artifacts:
    - image: saloni-test-image
      context: src
      sync:
        infer:
        - '**/*'
      docker:
        dockerfile: Dockerfile