apiVersion: apps/v1
kind: Deployment
metadata:
  name: saloni-web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: saloniweb1
        image: saloni-test-image
        ports:
        - containerPort: 80